### PR TITLE
Add str literal mutation

### PR DESCRIPTION
**Pull request by samgoldman**
If you're open to new mutations, I created a mutator for string literals. It replaces empty strings with a single character string and for non-empty strings it does a few things: append and prepend a single character as well as replacing the string with an empty string. I'd welcome any feedback. Thanks!

### CODE REVIEW

**Comment by samuelpilz** [comment]
This seems like a really good implementation of a new mutation, thank you. Documentation and tests are well done.
The only thing that concerns me is the owned String as return value from the `run` function. Generally, changing the type of an expression is tricky, it messes with type-inference and could result in different trait resolutions.

One potential issue in particular: Does this implementation break code like this (because the owned String is only a temp variable)?

```rust
fn a() -> usize {let x = ""; x.len()}
```

I suggest using a return value of `&'static str`. This requires baking the possible mutation literals into the source code.

**Comment by samgoldman** [comment]
Thanks for the feedback, that makes sense. I made the update, although I had to remove the appending and prepending mutations. I also added a test case for the example you provided and it doesn't break it (and it didn't break before changing to `&'static str` either).

**Comment by samuelpilz** [comment]
Indeed, for some reason `{let x = &String::new(); x.len()}` works (for some reason, the lifetime of the tempvar gets extended). I thought this was a minimal example of lifetime extension. Probably a better example is:

```rust
fn a() -> &'static str {""}
```

This code should not break as well (which is now fixed).


I really liked the string-dependent mutations. My idea is changing the signature of `run` roughly to:

```rust
fn run(
    mutator_id: usize,
    original_lit: &'static str,
    mutations: &[&'statc str],
    runtime: &impl Deref<Target = MutagenRuntimeConfig>,
)  -> &'static str {...}
```
This allows you to create the mutated strings at compile-time and have them available at run-time as `&'static str`

**Comment by samgoldman** [comment]
Yeah, the new example would have broken the original version. I updated to the signature you suggested and that example works (and I've added it as a test case).

**Comment by samuelpilz** [comment]
Great. One last comment: could you revert the documentation to your original proposal?
Otherwise, this is ready for merge (although I don't have the rights)

**Comment by samgoldman** [comment]
I forgot to leave a comment but that should be done.

**Comment by llogiq** [comment]
Thank you! I didn't have the time to look at this until now, but Samuel has already given all the feedback needed.

Thanks to both of you!

**Pull request merged**
