### PR TITLE
Setup Travis-CI

### PR DESCRIPTION
**Pull request by Keirua**
...as requested in #17 
There is not much to test for now, but it's done on Travis-CI ;)

@llogiq you'll have to enable it inside Travis I guess.

### CODE REVIEW

**Comment by Keirua** [comment]
Then we'll be able to pride ourselves with the infamous build badge
```markdown
[![Build Status](https://travis-ci.org/llogiq/mutagen.svg)](https://travis-ci.org/llogiq/mutagen) 
```

**Comment by llogiq** [comment]
Just activated it in Travis, I'll review shortly.

**Comment by llogiq** [comment]
Oops, should close+reopen this one...

**Comment by llogiq** [comment]
Thank you!

**Pull request merged**
