### PR TITLE
Fix eq and ne mutations 

### PR DESCRIPTION
**Pull request by gnieto**
The code generated for eq and non-eq binary operations was not correct.
There was an issue with the generated code.

Previously, the expression generated on the macro, where wrapping the
expression on a closure, but the closure does not implement PartialEq,
which is needed to be able to compare for equality/non-equality.

The code has been changed to receive a boxed closure which returns a
PartialEq. This is the unique way I've found to make an easy example
compile.

### CODE REVIEW

**Comment by llogiq** [comment]
I just came up with an even better idea: Use boolean operators to get rid of the closures altogether: `mutagen::now($n) || mutagen::now($n +1) && mutagen::now($n + 2) != ($left == $right)`

**Comment by gnieto** [comment]
The solution was much more easy, I guess. I've changed the fix by just removing the closures arrround eq and ne: 65bed02665871a23fd658e082faf51908c02b859

The error I was getting was this one:
```
error[E0277]: the trait bound `[closure@tests/binops.rs:16:32: 16:36]: std::cmp::PartialEq` is not satisfied
  --> tests/binops.rs:16:20
   |
16 |     if mutagen::t((mutagen::eq(|| 2, || 3, 18usize)), 15usize) {}
   |                    ^^^^^^^^^^^ can't compare `[closure@tests/binops.rs:16:32: 16:36]` with `[closure@tests/binops.rs:16:32: 16:36]`
   |
   = help: the trait `std::cmp::PartialEq` is not implemented for `[closure@tests/binops.rs:16:32: 16:36]`
   = note: required by `mutagen::eq`
```

There was any reason on having that closures? I'm missing something?

**Comment by llogiq** [comment]
There's a subtle distinction: Evaluation. With both the closures and the `&&`/`||` shenanigans the left and right side are not evaluated unless needed. This may actually make a difference if they have side-effects, e.g. `foo(stack.pop()) && bar(stack.pop())`. Evaluating the functions no matter what would change semantics in those cases, and we should be careful not to do that.

I wonder if we should split the mutation into "don't evaluate at all" and "evaluate and ignore the result".

**Comment by gnieto** [comment]
Ok, I think i finally got it.

I've maintained the closure, I've fixed the type of the closure and I'm invoking the closure when it's needed (as the "and" or "or" mutation).
I've also added a test to ensure that it works on expressions which has side-effects.

Hopefully, this will solve all the issues.

**Comment by llogiq** [comment]
Looks good to me.

**Pull request merged**
